In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3,4,5],[3,6,5,4,6]])
print(b)

[[1 2 3 4 5]
 [3 6 5 4 6]]


In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [8]:
a.shape

(3,)

In [9]:
b.shape

(2, 5)

In [10]:
a.dtype

dtype('int32')

In [14]:
a.itemsize

4

In [12]:
a.size

3

In [13]:
a.nbytes

12

In [16]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
x[1,5]

13

In [21]:
# Get a specific row
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column 
x[:, 0]

array([1, 8])

In [35]:
# Getting a little more fancy [startindex:endindex:stepsize]
x[0, 0:6:2]

array([1, 3, 5])

In [36]:
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [37]:
x[:, 2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
# b[0,1,0]
b[1,0,0]

5

1