### Initializing Different Types of Arrays

In [2]:
import numpy as np

In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
# All 1s matrix
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
# Any other number
np.full((2,2), 20)

array([[20, 20],
       [20, 20]])

In [ ]:
# Any other number (full_like)
np.full()

In [27]:
# Random deciaml numbers 
a = np.random.rand(4,2)
a

array([[0.69724565, 0.51002268],
       [0.07454736, 0.20196114],
       [0.96278653, 0.50514451],
       [0.38221863, 0.33256293]])

In [28]:
b = a*10
b

array([[6.97245648, 5.10022678],
       [0.74547357, 2.01961139],
       [9.62786529, 5.05144514],
       [3.82218634, 3.32562926]])

In [29]:
c = b // 1
c

array([[6., 5.],
       [0., 2.],
       [9., 5.],
       [3., 3.]])

In [39]:
# Random Integer Values
np.random.randint(0, 9)

5

In [3]:
# Random Integer Values
np.random.randint(7)

4

In [44]:
# Random Integer Values 
np.random.randint(7, shape*(3,3))

NameError: name 'shape' is not defined