### Load NumPy

In [1]:
import numpy as np

### NumPy Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b = np.array([[1,2,3,4,5],[3,6,5,4,6]])
print(b)

[[1 2 3 4 5]
 [3 6 5 4 6]]


In [4]:
a.ndim

1

In [5]:
b.ndim

2

In [6]:
a.shape

(3,)

In [7]:
b.shape

(2, 5)

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [11]:
a.nbytes

12

In [12]:
x = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
x[1,5]

13

In [14]:
# Get a specific row
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column 
x[:, 0]

array([1, 8])

In [16]:
# Getting a little more fancy [startindex:endindex:stepsize]
x[0, 0:6:2]

array([1, 3, 5])

In [17]:
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [18]:
x[:, 2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [19]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
# b[0,1,0]
b[1,0,0]

5

### Initializing Different Types of Arrays

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All 0s matrix
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [23]:
# All 1s matrix
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
# Any other number
np.full((2,2), 20)

array([[20, 20],
       [20, 20]])

In [25]:
# Any other number (full_like)
np.full(a.shape, 4)

array([4, 4, 4])

In [26]:
# Random deciaml numbers 
a = np.random.rand(4,2)
a

array([[0.11561066, 0.14313514],
       [0.67193128, 0.16209868],
       [0.74311439, 0.97126319],
       [0.00820651, 0.16614425]])

In [27]:
b = a*10
b

array([[1.15610658, 1.43135143],
       [6.71931276, 1.6209868 ],
       [7.4311439 , 9.71263192],
       [0.08206511, 1.66144251]])

In [28]:
c = b // 1
c

array([[1., 1.],
       [6., 1.],
       [7., 9.],
       [0., 1.]])

In [29]:
# Random Integer Values
np.random.randint(0, 9)

4

In [30]:
# Random Integer Values
np.random.randint(10, 20, size=(3,3))

array([[16, 14, 14],
       [10, 15, 16],
       [15, 12, 10]])

In [31]:
# The identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
# Array-1
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [33]:
# Array-2
arr = np.array([[8, 5, 2]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[8 5 2]
 [8 5 2]
 [8 5 2]]


In [34]:
output = np.ones((5,5))

z = np.zeros((3,3))
z[1,1] = 9

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be Careful When Copying Arrays

In [35]:
a = np.array([1,2,3,4])
# b = a
b = a.copy()
a[0] = 100

In [36]:
b

array([1, 2, 3, 4])

### Mathematics

In [37]:
a = np.array([1,2,3,4])

In [38]:
print(a)

[1 2 3 4]


In [39]:
a + 2

array([3, 4, 5, 6])

In [40]:
a - 1

array([0, 1, 2, 3])

In [41]:
a * 2

array([2, 4, 6, 8])

In [42]:
a ** 2

array([ 1,  4,  9, 16])

In [43]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [44]:
b = [4,3,2,1]

In [45]:
a + b

array([5, 5, 5, 5])

In [46]:
# Take sin of all values 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [47]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

https://docs.scipy.org/doc/numpy/reference/routines.math.html/

### Linear Algebra

In [48]:
a = np.ones((2,3))

In [49]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [50]:
b = np.full((3,2),2)

In [51]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [52]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [53]:
c = np.identity(3)

In [54]:
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# Find the determinent
np.linalg.det(c)

1.0

https://docs.scipy.org/doc/numpy/reference/routines.linalg.html/

### Statistics

In [56]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
np.min(stats)

1

In [58]:
np.max(stats)

6

In [59]:
np.min(stats, axis=1)

array([1, 4])

In [60]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [61]:
np.sum(stats)

21

### Reorganizing Arrays

In [62]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [63]:
after = before.reshape(4, 2)
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [65]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
Loading Data From File

In [67]:
filedata = np.genfromtxt('numpy_data.txt', delimiter=',')
filedata

array([[42., 83., 54., 37., 75., 33., 14., 43., 63., 23., 65., 58.],
       [67., 62., 55., 95., 64., 95., 76., 34., 76., 23., 57., 64.],
       [57., 76., 32., 78., 23., 64., 25., 75., 35., 77., 43., 24.]])

In [68]:
filedata = filedata.astype('int32')

In [69]:
filedata

array([[42, 83, 54, 37, 75, 33, 14, 43, 63, 23, 65, 58],
       [67, 62, 55, 95, 64, 95, 76, 34, 76, 23, 57, 64],
       [57, 76, 32, 78, 23, 64, 25, 75, 35, 77, 43, 24]])

### Boolean Masking and Advanced Indexing

In [70]:
filedata > 50

array([[False,  True,  True, False,  True, False, False, False,  True,
        False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True, False,  True,
        False,  True,  True],
       [ True,  True, False,  True, False,  True, False,  True, False,
         True, False, False]])

In [71]:
filedata[filedata > 50]

array([83, 54, 75, 63, 65, 58, 67, 62, 55, 95, 64, 95, 76, 76, 57, 64, 57,
       76, 78, 64, 75, 77])

In [72]:
## We can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8])
a[[1,2,7]]

array([2, 3, 8])

In [73]:
np.all(filedata > 50, axis=0)

array([False,  True, False, False, False, False, False, False, False,
       False, False, False])